language: java

## export GPG details
before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
    mvn --settings cfg/maven/CI/settings.xml clean install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

before_script:
    mvn cobertura:cobertura	

## Build and release to maven central  
script: 
    mvn deploy --settings cfg/maven/CI/settings.xml -DskipTests=true -B -U -Prelease

## Create release in GitHub
deploy:
  provider: script
  script: cfg/maven/CI/deploy.sh
  overwrite: true
  skip_cleanup: true
  on:
    repo: kicksolutions/swagger2puml
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - sontosh.mvs@gmail.com