## Java is Language
language: java

## Get the project version
before_deploy:
   - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
   - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

## Create release in GitHub
deploy:
  provider: releases
  api_key:
    secure: gsDkBDKHKiHhSGJ2LF2rIt4pXuTIQ3AsZ6ZP0srJOHCoK1CMIEtvhY+UOkPtyw1c5Ygz3isHnVmlW40fErnbojkrBJvWAAhlJWwdWtQrO6VVYeHui/fWJeNVc9kWVC8B7cAUhTSt7yX/NaMivuII8OCjr2Z1vXzSZz+B9URQndQPOZyopQZ11qeVRhHk9NObrTTMuQ1pvtyji2wdTObkg59lD/P1789Myz76jlXo6tSqU/A9Wbc6htBPjE2DtmKoQOTaYF1v0AVV5iphB7w4TT7nJvd8tPSw/9gXg1Dk+Dzdw9yaRZow2SkeNe0QykHAtoskBsGg0+kiycfOO9wQJT4E3BN8ROqwNZzUl4+HYIi+lH0DQmNoxd4WMNA2k1Dy6ZUHMf6y/06JJy6+PbkWjRkH9k/LxOtJdGtOz0zFV+zGi6BViV1tvy9HrXlqrrxmkB7hgaWdk9oh0L5Zg/qRbPBLoh2FIJAEX2w97o05v5G5qqZH2uXqVoC9nJ+2/GeXl0yPA6RBTdPVBvrSCIxTnhQ9hfqsZBrMzYDaBn/Wv8QwO4VSQC19a7VF9OCZ4+bmYUfUiJzXLVGLsxwVW1Z9C3wknu/Esxpk1jL5a6DyjnZk1hvW9QGtJ4iKFizc70OPh2xQ5oYWoktlEJs6lBi6KBvN4JTKz4TIvNGrWoVC3vk=
  file:
        - apiee-core/target/apiee-core-$project_version.jar
        - apiee-providers/target/apiee-providers-$project_version.jar
        - apiee-example/target/apiee-example.war
    skip_cleanup: true
  on:
    repo: kicksolutions/swagger2puml
  name: $project_version  