language: java

script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_BUILD_DIR
  - echo $(basename /home/travis/build/kicksolutions/swagger2puml)
  - find /home/travis/build/kicksolutions/swagger2puml -type f -printf "%f\n"

## Get the project version
before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

## Create release in GitHub
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: "$GITHUB_OAUTH_TOKEN"
  file: swagger2puml-core\target\swagger-plantuml-core-$project_version.jar
  skip_cleanup: true
  on:
    repo: kicksolutions/swagger2puml
  name: $project_version