language: java

script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_BUILD_DIR
  - echo $(basename /home/travis/build/kicksolutions/swagger2puml)
  - find /home/travis/build/kicksolutions/swagger2puml -type f -printf "%f\n"
  - find /dir -type f -follow -print|xargs ls -l

## Get the project version
before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

## Create release in GitHub
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: KFRFdMpy8NKUC8GwvJ5SdqBjncDVe9RD+uzeAbB3XqRx8O8jpWIRdMumEsq0ZvBXKDcft2TNjAQxMHBSOtCVP2MtG2WbKsFJxcFQa0FRiIi2PHb2cfMEAhpRChVMglhyEMih5g4Y/bd8Lx/VtHzG0bBPQVjUsfbWt/bXdTxtFQF2XgLg17XANylj4nYaYc5T/cIAkDugLt1fG/A3Yf1s8m1V4xMRTEaqplrHvTqVa6pD1bL2X3Eyhdm+9XKEcGiWooq8yJF3Os6++V4YLxhNvukErnkoyOGk+y8hkAyMuyVoyPJfMfskwrEo+d2++D1tTmwm4bca/cXDzqK4J4tQ0XxyE5D524jH7BS2MvFki2o9SppyBp6CPMDgKrKfJFQVBsL1EIcjNpYwdGL7lPjyr8fEFsFjMqsqpdfvp9bj4GKPu5wk93qjfIqsavUsi176NSrKS2xZBk/KZb6DkWfOCt1BkGI+sxVStwcE49+VKPsayjM4EVlvJHITWb+8aPlXFeuQRK+IYjkX2npRhIuVAttax6SmKvHpSookNsH80YgnjPi/v2pDjUlIkhRdbLvxGHl0GyVLMASZOu+oeA1yR6cWrHtLv4vkdgK7HzPn0r74Cg/NWqG389BpAupujEmNAcknT9plvQVnh3R61CqfugZj/ydQjZFwr8NwO/oLE/g=
  skip_cleanup: true
  on:
    repo: kicksolutions/swagger2puml
    tags: true
  name: $project_version