language: java

## export GPG details
before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
    mvn --settings cfg/maven/CI/settings.xml clean install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

before_script:
    mvn cobertura:cobertura	

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: 
  	- echo Deploying Changes to Central Nexus
  	- mvn org.codehaus.mojo:versions-maven-plugin:2.3:set -DnewVersion=$TRAVIS_TAG
  	- mvn deploy --settings cfg/maven/CI/settings.xml -DskipTests=true -B -U -Prelease
  on:
    tags: true

notifications:
  email:
    - sontosh.mvs@gmail.com