language: java

jdk:
  - oraclejdk8

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V

deploy:
 	- 
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: kicksolutions/swagger2puml
      branch: master
      jdk: oraclejdk8
  - 
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: kicksolutions/swagger2puml
      tags: true
      jdk: oraclejdk8

notifications:
  email:
    - sontosh.mvs@gmail.com