language: java
install: true

## Get the project version
before_deploy:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

## Build and release to maven central  
script: 
    mvn clean deploy --settings cfg/maven/CI/settings.xml -DskipTests=true -B -U -Prelease

## Create release in GitHub
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: KFRFdMpy8NKUC8GwvJ5SdqBjncDVe9RD+uzeAbB3XqRx8O8jpWIRdMumEsq0ZvBXKDcft2TNjAQxMHBSOtCVP2MtG2WbKsFJxcFQa0FRiIi2PHb2cfMEAhpRChVMglhyEMih5g4Y/bd8Lx/VtHzG0bBPQVjUsfbWt/bXdTxtFQF2XgLg17XANylj4nYaYc5T/cIAkDugLt1fG/A3Yf1s8m1V4xMRTEaqplrHvTqVa6pD1bL2X3Eyhdm+9XKEcGiWooq8yJF3Os6++V4YLxhNvukErnkoyOGk+y8hkAyMuyVoyPJfMfskwrEo+d2++D1tTmwm4bca/cXDzqK4J4tQ0XxyE5D524jH7BS2MvFki2o9SppyBp6CPMDgKrKfJFQVBsL1EIcjNpYwdGL7lPjyr8fEFsFjMqsqpdfvp9bj4GKPu5wk93qjfIqsavUsi176NSrKS2xZBk/KZb6DkWfOCt1BkGI+sxVStwcE49+VKPsayjM4EVlvJHITWb+8aPlXFeuQRK+IYjkX2npRhIuVAttax6SmKvHpSookNsH80YgnjPi/v2pDjUlIkhRdbLvxGHl0GyVLMASZOu+oeA1yR6cWrHtLv4vkdgK7HzPn0r74Cg/NWqG389BpAupujEmNAcknT9plvQVnh3R61CqfugZj/ydQjZFwr8NwO/oLE/g=
  skip_cleanup: true
  on:
    repo: kicksolutions/swagger2puml
    tags: true
  name: $project_version

notifications:
  email:
    on_success: change
    on_failure: change
    - sontosh.mvs@gmail.com  